# Generated by Django 3.2.20 on 2023-07-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='lat',
            field=models.CharField(default='12.1234', max_length=20),
        ),
        migrations.AlterField(
            model_name='house',
            name='lng',
            field=models.CharField(default='10.1234', max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='floor_type',
            field=models.CharField(choices=[('UP', '고층'), ('MID', '중층'), ('LOW', '저층'), ('UNDER', '반지하')], max_length=10),
        ),
        migrations.AlterField(
            model_name='review',
            name='house_type',
            field=models.CharField(choices=[('OpenOneRoom', '오픈형 원룸'), ('SepOneRoom', '분리형 원룸'), ('OfficeTel', '오피스텔'), ('Duplex', '복층'), ('TwoRoom', '투룸')], default='OpenOneRoom', max_length=20),
        ),
    ]
