# Generated by Django 3.2.20 on 2023-08-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zip', '0002_auto_20230728_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='key_type',
            field=models.CharField(choices=[('INFRA', 'Infrastructure'), ('ROOM', 'Room Condition'), ('SAFETY', 'Safety'), ('TRANSPORT', 'Transportation')], max_length=10),
        ),
    ]
