# Generated by Django 3.2.20 on 2023-07-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercontrol', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='interested_reviews',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='major',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
