# Generated by Django 3.2.20 on 2023-08-10 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usercontrol', '0003_auto_20230728_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='major',
            new_name='department',
        ),
    ]
