# Generated by Django 3.2.20 on 2023-07-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usercontrol', '0001_initial'),
        ('zip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='interested_areas',
            field=models.ManyToManyField(blank=True, related_name='interested_users', to='zip.Area'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='interested_houses',
            field=models.ManyToManyField(blank=True, related_name='interested_users', to='zip.House'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='interested_reviews',
            field=models.ManyToManyField(blank=True, related_name='interested_users', to='zip.Review'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
