# Generated by Django 3.2.20 on 2023-07-24 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('area_code', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('area_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(unique=True)),
                ('lat', models.CharField(default='12.1234', max_length=12)),
                ('lng', models.CharField(default='10.1234', max_length=12)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('review_num', models.IntegerField(default=1)),
                ('interest_num', models.IntegerField(default=0)),
                ('suggest_ratio', models.FloatField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='houses', to='zip.area')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_type', models.CharField(choices=[('INFRA', 'Infrastructure'), ('ROOM', 'Room Condition'), ('SAFETY', 'Safety'), ('TRANSPORT', 'Transportation method')], max_length=10)),
                ('description', models.CharField(max_length=50)),
                ('icon_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_type', models.CharField(choices=[('UP', 'UPPER'), ('MID', 'MIDDLE'), ('LOW', 'LOWER'), ('UNDER', 'UNDERGROUND')], max_length=10)),
                ('exit_year', models.IntegerField(null=True)),
                ('house_type', models.CharField(max_length=20)),
                ('rent_type', models.CharField(max_length=10)),
                ('deposit', models.IntegerField()),
                ('monthly', models.IntegerField(null=True)),
                ('maintenance', models.IntegerField()),
                ('merits', models.TextField()),
                ('demerits', models.TextField()),
                ('img_url', models.URLField()),
                ('rating_inside', models.IntegerField()),
                ('rating_transport', models.IntegerField()),
                ('rating_infra', models.IntegerField()),
                ('rating_safety', models.IntegerField()),
                ('rating_overall', models.IntegerField()),
                ('suggest', models.BooleanField()),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='zip.house')),
                ('keywords', models.ManyToManyField(blank=True, related_name='reviews', to='zip.Keyword')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
